name: blacklist-service

services:
  blacklist-service:
    container_name: blacklist-service
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_PORT: 5006
    ports:
      - "5006:5006"
    env_file:
      - .env # NEW_RELIC_LICENSE_KEY=
    environment:
      FLASK_ENV: development
    deploy:
      resources:
        reservations:
          cpus: "2"
          memory: 2G
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
        - action: rebuild
          path: .env
