version: '3.8'

services:
  blacklist-service:
    build: .
    container_name: blacklist-service
    ports:
      - "80:80"
    environment:
      FLASK_ENV: development
    volumes:
      - .:/app
    networks:
      - app_net

networks:
  app_net:
